#spring:
#  application:
#    name: APIs
#
#  datasource:
#    url: jdbc:postgresql://localhost:5432/attachaki
#    username: postgres
#    password: suffu7x
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
